### ISSUE TITLE
Debug?

### ISSUE THREAD

**Issue by miztizm** [Sheape/metamask-bruteforce#2]
First and foremost, the script is excellently crafted, and I'm quite fond of it. Occasionally, it does shut down, but I've mitigated this by creating a .bat file to restart it whenever necessary, so that's not a major issue. The primary concern arises when I use a program installed or compiled from source. It often displays only a black screen, doing nothing further, and sometimes it even shuts down after a while. To rectify this, I believe I need to uninstall cargo and reinstall everything, though I'm not entirely certain. Additionally, I'm curious about the consequences if one of the API keys becomes inactive. How can I troubleshoot to determine the cause of the program's failure to start? Any assistance would be greatly appreciated.

**Comment by Sheape** [comment]
> First and foremost, the script is excellently crafted, and I'm quite fond of it. Occasionally, it does shut down, but I've mitigated this by creating a .bat file to restart it whenever necessary, so that's not a major issue. The primary concern arises when I use a program installed or compiled from source. It often displays only a black screen, doing nothing further, and sometimes it even shuts down after a while. To rectify this, I believe I need to uninstall cargo and reinstall everything, though I'm not entirely certain. Additionally, I'm curious about the consequences if one of the API keys becomes inactive. How can I troubleshoot to determine the cause of the program's failure to start? Any assistance would be greatly appreciated.

It's not really a script, its a binary. Anyways, I just made this as a side project in the past. Sometimes it fails to start due to one of the API's request taking way too long to respond (most likely, moonriver or optimism). It also crash sometimes because even though a wallet doesn't exist, the API for moonriver and optimism will return null. I was also using rust nightly instead of regular version which probably explains why you have to reinstall everything. Not gonna lie, I havent really gotten anything with this program. I'm currently busy with other stuff, so I wouldn't be able to debug or fix issues with this though pull request are always open :>
